# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-06 08:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Cake Name')),
                ('flavor', models.CharField(blank=True, max_length=200, verbose_name='Cake Flavor')),
                ('price', models.IntegerField()),
                ('minsize', models.IntegerField()),
                ('brand', models.CharField(max_length=200, verbose_name='Cake Brand')),
                ('image', models.ImageField(upload_to=product.models.get_cake_image_path, verbose_name='Cake Image')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Category Name')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='cake',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cakes', to='product.Category'),
        ),
        migrations.AlterUniqueTogether(
            name='cake',
            unique_together=set([('category', 'name')]),
        ),
    ]
