# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-06 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cake',
            options={'get_latest_by': 'created_on', 'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='cake',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
