# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-23 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20161206_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='CakeFlavor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Cake Flavor')),
                ('additional_price_per_pound', models.IntegerField(verbose_name='Cake flavor')),
            ],
        ),
        migrations.CreateModel(
            name='CakeShape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Cake Shape')),
                ('additional_price_per_pound', models.IntegerField(verbose_name='Extra Charge')),
            ],
        ),
        migrations.RemoveField(
            model_name='cake',
            name='flavor',
        ),
        migrations.AddField(
            model_name='cake',
            name='shape',
            field=models.ManyToManyField(to='product.CakeShape'),
        ),
        migrations.AddField(
            model_name='cake',
            name='flavor',
            field=models.ManyToManyField(to='product.CakeFlavor'),
        ),
    ]
