# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-05 15:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0003_auto_20170123_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=256)),
                ('cake_size', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantity', models.IntegerField()),
                ('cake_flavor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.CakeFlavor')),
                ('cake_shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.CakeShape')),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='When was cake ordered')),
                ('total_price', models.FloatField(verbose_name='Checkout billing amount')),
                ('delivery_time', models.DateTimeField(verbose_name='When to deliver')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=500, verbose_name='address')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryReceiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='receiver name')),
                ('phone_number', models.CharField(max_length=40, verbose_name='receiver phone number')),
            ],
        ),
        migrations.AddField(
            model_name='checkout',
            name='delivery_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.DeliveryLocation'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='items',
            field=models.ManyToManyField(through='product.CartItem', to='product.Cake'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.DeliveryReceiver'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='checkout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Checkout'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Cake'),
        ),
    ]
