# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-09 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20170205_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='/media_root/cakePics/78. Logo topping chocolate 3 lb.JPG', upload_to=product.models.get_cake_image_path, verbose_name='Cake Image'),
            preserve_default=False,
        ),
    ]
