# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-12 13:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20170212_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryreceiver',
            name='phone_number',
            field=models.CharField(max_length=40, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?\\d{9,15}$')], verbose_name="Receiver's phone number"),
        ),
    ]
