# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-13 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_checkout_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverylocation',
            name='client',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='is_eggless',
            field=models.BooleanField(default=False, verbose_name='Eggless'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartitem',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
