# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-12 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20170213_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cakeflavor',
            name='additional_price_per_pound',
            field=models.IntegerField(verbose_name='Extra Price'),
        ),
    ]
