# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-21 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20170213_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('verified', 'verified'), ('delivered', 'delivered'), ('rejected', 'rejected')], default='pending', max_length=20, verbose_name='Checkout Status'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cakeflavor',
            name='additional_price_per_pound',
            field=models.IntegerField(verbose_name='Extra Price'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to=product.models.get_category_image_path, verbose_name='Cake Image'),
        ),
    ]
