# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-22 07:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20170421_1812'),
        ('product', '0010_auto_20170412_1945'),
    ]

    operations = [
    ]
