# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-26 07:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cakes', to='product.Category'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cake_flavor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.CakeFlavor'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cake_shape',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.CakeShape'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='checkout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Checkout'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Cake'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='delivery_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.DeliveryLocation'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.DeliveryReceiver'),
        ),
    ]
