# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-29 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20170526_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='secondary_receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='secondary_receiver', to='product.DeliveryReceiver'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkout',
            name='message',
            field=models.CharField(max_length=500, verbose_name='Message (For receiver not written on Cake)'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_receiver', to='product.DeliveryReceiver'),
        ),
    ]
