# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-30 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20170529_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='best_selling',
            field=models.BooleanField(default=False, verbose_name='Best Selling'),
        ),
    ]
