# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-22 18:52
from __future__ import unicode_literals

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20180506_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='carousel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='carousel_image',
            field=models.ImageField(blank=True, upload_to=product.models.get_category_carousel_image_path, verbose_name='Carousel Image'),
        ),
        migrations.AddField(
            model_name='category',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to=product.models.get_category_image_path, verbose_name='Cake Image'),
        ),
    ]
