# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-01 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_category_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
