# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-04 09:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_cake_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cake',
            unique_together=set([]),
        ),
    ]
