# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-06 05:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

def move_category_to_categories(apps, schema_editor):
    Cake = apps.get_model("product", "Cake")
    for cake in Cake.objects.all():
        print("Updating categories for cake {}".format(cake.name))
        cake.categories.add(cake.category)
        print("Updating categories for cake {} Success".format(cake.name))
    print("Updating categories for all cakes")


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_auto_20190704_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='categories',
            field=models.ManyToManyField(related_name='cakes', to='product.Category'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cake', to='product.Category'),
        ),
        migrations.RunPython(move_category_to_categories)
    ]
