# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-06 05:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_auto_20190706_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='category',
        ),
    ]
