# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-03 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0011_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('COD', 'Cash on Delivery'), ('PAYPAL', 'Paypal')], max_length=10, verbose_name='Payment method')),
                ('reference_code', models.CharField(default='', max_length=100, verbose_name='Reference Code')),
                ('checkout', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment_method', to='product.Checkout')),
            ],
        ),
    ]
