# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-05 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Payment Received'),
            preserve_default=False,
        ),
    ]
